### ISSUE TITLE
Rails 5 support

### ISSUE THREAD

**Issue by craig-day** [grosser/forking_test_runner#5]
Can you add rails 5 support?

**Comment by grosser** [comment]
add a rails 5 gemfile and see if it works :D

**Comment by mrteera** [comment]
I use Rails 5 and I got this errors:

```
$ forking-test-runner test/controllers/youtube_trends_controller_test.rb                                                                                              [20:24:20]
[Coveralls] Outside the CI environment, not sending data.
/Users/mrteera/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require': cannot load such file -- parallel_tests/test/runner (LoadError)
       	from /Users/mrteera/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `block in require'
       	from /Users/mrteera/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
       	from /Users/mrteera/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
       	from /Users/mrteera/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/forking_test_runner-0.7.1/lib/forking_test_runner.rb:281:in `find_tests_for_group'
       	from /Users/mrteera/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/forking_test_runner-0.7.1/lib/forking_test_runner.rb:61:in `cli'
       	from /Users/mrteera/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/forking_test_runner-0.7.1/bin/forking-test-runner:8:in `<top (required)>'
       	from /Users/mrteera/.rbenv/versions/2.3.1/bin/forking-test-runner:23:in `load'
       	from /Users/mrteera/.rbenv/versions/2.3.1/bin/forking-test-runner:23:in `<main>'
```

**Comment by grosser** [comment]
try with `bundle exec`

**Comment by grosser** [comment]
works just fine on samson which is on rails 5 ...
