### ISSUE TITLE
RuntimeError: Load minitest after setting up SingleCov (single_cov + minitest)

### ISSUE THREAD

**Issue by dadah89** [grosser/forking_test_runner#9]
test_helper.rb
```rb
# frozen_string_literal: true

ENV['RAILS_ENV'] = 'test'

require 'single_cov'

SingleCov.setup :minitest

require 'bundler/setup'
...
```

```
(2.4.2) vagrant: $ bundle exec forking-test-runner test --groups 5 --group 4
bundler: failed to load command: forking-test-runner (/home/vagrant/bundle/ruby/2.4.0/bin/forking-test-runner)
RuntimeError: Load minitest after setting up SingleCov
  /home/vagrant/bundle/ruby/2.4.0/gems/single_cov-0.7.0/lib/single_cov.rb:137:in `minitest_should_not_be_running!'
  /home/vagrant/bundle/ruby/2.4.0/gems/single_cov-0.7.0/lib/single_cov.rb:70:in `setup'
  /harmony/code/rosetta/test/test_helper.rb:7:in `<top (required)>'
...
```

It works with `--merge-coverage`.  Without it, it seems it'll always fail no matter what.

**Comment by grosser** [comment]
using forking test runner without merge-coverage makes the coverage completely useless anyway (since it would start out as all uncovered even though a file was already loaded during setup) ... so there is no real need for this to work ... 

pushed a patch to fail nicer
